<?php
/**
 * @var DefaultRenderer $block
 * @var LocaleFormatter $localeFormatter
 * @var Escaper         $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\Locale\LocaleFormatter;
use Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer;

$item = $block->getItem();
?>
<tr id="order-item-row-<?= (int) $item->getId() ?>">
    <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $escaper->escapeHtml($item->getName()) ?></strong>
        <?php if ($options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($options as $option): ?>
                    <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $formattedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dd<?= (isset($formattedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?= $escaper->escapeHtml($formattedOptionValue['value'], ['a']) ?>
                            <?php if (isset($formattedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                                        <dd><?= $escaper->escapeHtml($formattedOptionValue['full_view']) ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <?php $optionValue = $option['print_value'] ?? $option['value'] ?>
                        <dd><?= $escaper->escapeHtml($optionValue) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($item)->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')) ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?></span>
                    <span class="content">
                    <?= $escaper->escapeHtml($localeFormatter->formatNumber((float) $block->getItem()->getQtyOrdered())) ?>
                </span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?></span>
                    <span class="content">
                    <?= $escaper->escapeHtml($localeFormatter->formatNumber((float) $block->getItem()->getQtyShipped())) ?>
                </span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?></span>
                    <span class="content">
                    <?= $escaper->escapeHtml($localeFormatter->formatNumber((float) $block->getItem()->getQtyCanceled())) ?>
                </span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?></span>
                    <span class="content">
                    <?= $escaper->escapeHtml($localeFormatter->formatNumber((float) $block->getItem()->getQtyRefunded())) ?>
                </span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
