<?php
/**
 * @var Downloadable    $block
 * @var Escaper         $escaper
 * @var LocaleFormatter $localeFormatter
 */

use Magento\Framework\Escaper;
use Magento\Framework\Locale\LocaleFormatter;
use Oggetto\BestProduct\Block\Order\Item\Renderer\Downloadable;

?>
<?php $_item = $block->getItem() ?>
<tr id="order-item-row-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
    <td class="col name" data-th="<?= $escaper->escapeHtmlAttr(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $escaper->escapeHtml($_item->getName()) ?></strong>
        <?php if ($options = $block->getItemOptions()): ?>
            <dl class="item-options links">
                <?php foreach ($options as $option): ?>
                    <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $formattedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dd<?php if (isset($formattedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                            <?= /* @noEscape */ $formattedOptionValue['value'] ?>
                            <?php if (isset($formattedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                                        <dd><?= /* @noEscape */ $formattedOptionValue['full_view'] ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd><?= /* @noEscape */ nl2br(($option['print_value'] ?? $option['value'])) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php if ($links = $block->getLinks()): ?>
            <dl class="item-options links">
                <dt><?= $escaper->escapeHtml($block->getLinksTitle()) ?></dt>
                <?php foreach ($links->getPurchasedItems() as $link): ?>
                    <dd><?= $escaper->escapeHtml($link->getLinkTitle()) ?></dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* EOF downloadable */ ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $escaper->escapeHtmlAttr(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col is-best" data-th="<?= $escaper->escapeHtml(__('Is Best')) ?>">
        <?= $escaper->escapeHtml($block->getIsBest()) ?>
    </td>
    <td class="col price" data-th="<?= $escaper->escapeHtmlAttr(__('Price')) ?>"><?= $block->getItemPriceHtml() ?></td>
    <td class="col qty" data-th="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?></span>
                    <span class="content">
                        <?= $escaper->escapeHtml($localeFormatter->formatNumber((float) $block->getItem()->getQtyOrdered() * 1)) ?>
                    </span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyShipped() * 1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyCanceled() * 1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyRefunded() * 1 ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $escaper->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
