<?php
/**
 * @var ListNews $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Oggetto\News\Api\Data\NewsInterface;
use Oggetto\News\Block\News\ListNews;

?>
<div class="news">
    <?php $newsCollection = $block->getCollection(); ?>
    <?php if ($newsCollection->getSize() > 0) : ?>
        <ul>
            <?php /** @var NewsInterface $news */
            foreach ($newsCollection as $news) : ?>
                <li>
                    <div class="news-list">
                        <a class="news-title" href="<?= $this->getUrl('news/news/view',
                            [NewsInterface::ID => $news->getId()]); ?>"><?= $news->getTitle(); ?></a>
                        <div class="news-list-content">
                            <?= $news->getDescription(); ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>

        <div style="clear: both"></div>

        <div class="toolbar-bottom">
            <div class="toolbar bottom">
                <?= $block->getPagerHtml(); ?>
            </div>
        </div>
    <?php else : ?>
        <p><?= __('Have no news!'); ?></p>
    <?php endif; ?>
</div>
